import Home from './HomePage'
import SingleRoom from './SingleRoomPage'
import Room from './RoomsPage'
import About from './AboutPage'
import Readme from './ReadmePage'
import BookingHistory from './BookingHistoryPage'
import Error from './ErrorPage'
import PrivateRoute from './PrivateRoute'
import AdminRoute from './AdminRoute'
import AuthWrapper from './AuthWrapper'
import Login from './LoginPage'
import Logout from './LogoutPage'
import Register from './RegisterPage'
import ChangePassword from './ChangePasswordPage'

import Admin from './AdminPage'
import AdminUser from './AdminUserPage'
import AdminRoom from './AdminRoomPage'
import AdminBooking from './AdminBookingPage'

export { Home, SingleRoom, Room, About, Readme, BookingHistory, Error, PrivateRoute, AdminRoute, AuthWrapper, Login, Logout, Register, ChangePassword, Admin, AdminUser, AdminRoom, AdminBooking }
